### ISSUE TITLE
Extend build process to provide downloadable executables, and p2 update repository

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#117]
Limpet is almost ready for people to start playing with it.

If possible, I'd like you to extend the Travis build process to offer the following:
- build versions of Limpet in Win32, Win64, OSX64, Linux64, put them on the releases page
- a P2 repository to download Limpet updates
- a downloadable version of Limpet - from a fixed URL. This version of limpet should know the location of the P2 repository, allowing quick & easy updates

I believe we can use the gh-pages branch of the Limpet repository for hosting.

In the longer term, my "real users" will mostly use Limpet offline - but this would be valuable for these early steps.

**Comment by IanMayo** [comment]
@pecko - I'd like you to start this issue too, please.

**Comment by pecko** [comment]
I have prepared to add this feature.
You should to do the following:
- create a github project for update/release. It would contains only gh-pages.
  We can use original limpet, but it would be better to use another repository.
  I have tested with https://github.com/pecko/limpet-release because I don't have the permission to create a project in the debrief org
- create encrypted GH_TOKEN in the limpet repository as follows:

`
travis encrypt "GH_TOKEN=<some_debrief_api_key>" -r debrief/limpet
`
- decide what exactly you should add to this page. Currently, I just add update site, but you probably want to add the distribution archive (maybe with changed names)
- maybe we should add some index.html that would show releases and explain how to use the update site. For instance, if you try http://pecko.github.io/limpet-release/1.0 from browser you will get "missing page:, but it will work from Eclipse/Limpet/Debrief.

The current PR fails on travis because travis doesn't decrypt secure variable in PR. We will have to test this feature when applying the PR

Notice:
1) The update actions (Help>Check for Updates, Help>Install new software), as well as adding update site don't work in Eclipse PDE.

If you want to test you should pull the PR, build a distribution, start the distribution ...
Since, we have only version 1.0 you have to uncheck "Hide items that are already installed" in order to see limpet's feature.

2) You can also add the http://pecko.github.io/limpet-release/1.0 update site to pure eclipse or Debrief and install Limpet. 

3) We can use this update site in a target platform that require Limpet (Debrief when we want to add Limpet to Debrief).

**Comment by pecko** [comment]
I have changed update site to http://debrief.github.io/limpet-release/1.0
We still need valid secure key made with

```
travis encrypt "GH_TOKEN=<api-key>" -r debrief/limpet
```

and test it.

**Comment by pecko** [comment]
I have revert your commit https://github.com/debrief/limpet/commit/a80d3308d05ba6db8da227bdc3e1ba491662c38c#commitcomment-14807909 by rebasing the PR (will be active after applying the PR). 
We just need secure GH_TOKEN=...

**Comment by IanMayo** [comment]
Not back for a few hours.  But will need more detailed guidance.  Can you give me a link to a blog /help page that explains how to get the token?  
I must have done it for Debrief,  but can't remember...

**Comment by pecko** [comment]
Create api token: https://help.github.com/articles/creating-an-access-token-for-command-line-use/

You will get some API key like 'abcdef1234.....'

After that you can create encrypted variable with

```
travis encrypt "GH_TOKEN=abcdef1234" -r debrief/limpet
```

I have tried to use some my API key. It should work because I can push to limpet-release.
Also, I will try to skip this when build a PR in order to build pass in any case.

**Comment by pecko** [comment]
I have applied the PR in order to test.

**Comment by pecko** [comment]
It works with my api key.

**Comment by pecko** [comment]
Next steps:
- change secure variable to some your api key
- define what we should add yet (I suppose the release files for all OSes)
- create a index.html that will show release files and describe update site

**Comment by pecko** [comment]
BTW
You have test the http://debrief.github.io/limpet-release/1.0 update site

**Comment by IanMayo** [comment]
@pecko - I've just tried to test the update site, but it didn't work (yet)

Here's what I did:
- export pre-1.0.1 version of limpet (product & features all at 1.0.0)
- start application, check 1.0.1 feature not present (**Analysis View** doesn't recognise content-type of Location dataset from usa.csv)
- click on "Check for updates".  The dialog shows the app looking for an update, then says: **No updates were found**

Just to be sure, I tried to force the install:
- click on **Install new software**.  
- Select 1.0.1 versions of Limpet.  Try to install.  
- Limpet indicates error (shown below)

![selection_021](https://cloud.githubusercontent.com/assets/1108513/11680704/0616f9ee-9e52-11e5-8d87-43151ebb8804.png)

**Comment by IanMayo** [comment]
Oh, @pecko : please note -  I've changed the default branch of limpet-release to be gh-pages - since we will never be referring to the normal master branch.

I don't think this will affect the build process.

**Comment by pecko** [comment]
>  I've changed the default branch of limpet-release to be gh-pages - since we will never be referring to the normal master branch.

I suppose so. I think that we have to create the gh-pages as orphan branch (once) and it will be present as web page. Anyway, will check.

I will also test the issue with updating. Maybe, first distribution (1.0.0) isn't defined correctly (requires 1.0.0 feature) and we should try update from 1.0.1 to 1.0.2.

**Comment by pecko** [comment]
The commit https://github.com/pecko/limpet/commit/79037e457e23e397d596cc542ba69d187a4e7d14 should fix the Limpet update.

You can test in the following way:
- create a Limpet distribution using current master (Limpet 1.0.1)
- create Limpet version 1.0.2 (the example is in my testingupdate branch)
- try update from Limpet version 1.0.1 to 1.0.2

**Comment by pecko** [comment]
Updating works using "Help>Install new software", but "Help>Check for updates" doesn't work. I'm not sure that it is possible to solve without reconfiguring RCP features.
Please let me know if you think that it is important.

**Comment by IanMayo** [comment]
Yes, "Check for updates"  is important.

**Comment by pecko** [comment]
OK. Working on that. It is weird that update works and "Check for updates" doesn't work.

**Comment by pecko** [comment]
I have fixed the "Check for Updates" action (the PR is merged). There is still one update that currently doesn't work. 
You can see that updating limpet's features works as described above, but Limpet product id isn't updated. It will stay 1.0.1.
It also can be done but we will probably have to upload all features (Eclipse and Limpet) to update site. Would you like me to add that?

**Comment by IanMayo** [comment]
Hmm, we shouldn't have to upload Eclipse features, since they're not being updated.

I used to provide p2 updates for Debrief.  I'm sure I only used to include the Debrief plugins/features in the p2 site.

**Comment by pecko** [comment]
It mean I would try to add it too.
I can try to skip eclipse's features/plugins using script because we certainly know that it will not be required.

BTW
You also update only features/plugins in Debrief, but don't update Debrief product (ID and similar). Right?

**Comment by IanMayo** [comment]
Hmm,
I haven't delivered p2 update for Debrief for almost 2 years (old client).

I can't actually remember exactly if I had to increment the product id at each release.  But, I think I did.

The update procedure certainly includes updating the product number:
https://github.com/debrief/debrief/wiki/Getting-started-in-Debrief-development

**Comment by pecko** [comment]
I know that installing using distribution file will update product id, but I think that Debrief ID also will not be updated when using a update site. Actually, it is possible that update will not work at all. I have created first version of limpet build based on Debrief.

Maybe, it would be the best that you try. You will see that product id will stay the same (About->Installation details). IMO, it is just ID (maybe not important), but the user will not be sure what Limpet version he/she run.

**Comment by IanMayo** [comment]
@pecko - I'm sure it's important that we update the product ID.

We will certainly be updating the Product ID for the traditionally built versions.

I'd appreciate you carrying on investigating, please.

**Comment by pecko** [comment]
I will start it asap.

**Comment by pecko** [comment]
> We will certainly be updating the Product ID for the traditionally built versions.

https://github.com/debrief/limpet/pull/185 adds product to update site.
We have to test it after applying.
I have created the testingupdate branch for test. 

Steps to test:
- apply #185 
- create and install distribution
- create update site using the testing update branch
  The branch should also applied in order to create valid (1.0.2) update site. This branch just update product, features and plugins version
- update using Help>Check for Updates from distribution installed in step 2

**Comment by pecko** [comment]
The plugins directory isn't created. Checking...

**Comment by pecko** [comment]
I have fixed it and rebased test-increase-version

**Comment by pecko** [comment]
I have tested and it works fine now.

**Comment by IanMayo** [comment]
Update working fine!
