### ISSUE TITLE
Static code analysis tool

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#157]
I have registered for Coverity - which provides static code analysis. This may provide us with some quality improvements, for free.

But, I haven't put in the time to understand how to integrate it with our project.  But, it does integrate with Travis:
https://scan.coverity.com/travis_ci

I'll invite you to the Coverity project. Hopefully you can read up on it, and get our Limpet builds automatically

**Comment by pecko** [comment]
We could also try to use http://www.sonarqube.org/

**Comment by pecko** [comment]
There isn't a feedback on https://scan.coverity.com/projects/limpet. We probably would try other solution (sonar, checkstyle, pmd or similar).

**Comment by pecko** [comment]
Since there isn't any feedback from coverity site , we will try to integrate sonar and travis.

**Comment by pecko** [comment]
SonarQube requires dedicated server with Java. I suppose that we can't provide such server, for now. Because of that I have created standard maven reports for FindBugs, PMD and Checkstyle.
Test output: http://debrief.github.io/limpet-update/static/report/
The PR: https://github.com/debrief/limpet/pull/223

Notice: 
Checkstyle should be adapted to Debrief style.
CPD is part of PMD which shows code duplicates.

**Comment by pecko** [comment]
Screenshots:

![static1](https://cloud.githubusercontent.com/assets/534584/12081929/353c27a8-b289-11e5-84a2-552f7f2a0764.png)
![static2](https://cloud.githubusercontent.com/assets/534584/12081928/353c16d2-b289-11e5-9edf-8e37f3039acd.png)
![static3](https://cloud.githubusercontent.com/assets/534584/12081930/3542090c-b289-11e5-8bf0-1c79813591bb.png)
![static4](https://cloud.githubusercontent.com/assets/534584/12081931/3541dcf2-b289-11e5-9dff-85d7da8868f9.png)

**Comment by IanMayo** [comment]
@pecko - can we integrate test coverage in this reporting style?

**Comment by IanMayo** [comment]
@pecko  - for me to tune the CheckStyle settnigs, I want to run them locally.  

Our deply_ghpages task script currently collates the data. Is it possible for the data to be collated locally, so I can view them after an `mvn clean update`?

**Comment by pecko** [comment]
> - can we integrate test coverage in this reporting style?

Test coverage has created with jacoco ant task, but this reports are maven reports. We could try to convert test coverage to this style. I will also check if there is maven jacoco plugin.

> for me to tune the CheckStyle settnigs, I want to run them locally. 
> Our deply_ghpages task script currently collates the data. Is it possible for the data to be collated locally, so I can view them after an mvn clean update?

```
mvn clean verify site
```

will create these reports in <project_home>/target/site directories, but links between projects are broken. I have to fix that. You should check <project_home>/target/site/index.html or <project_home>/target/site/project_reports.html to review

**Comment by pecko** [comment]
http://debrief.github.io/limpet-update/static/report/ is correct now. Fixed with commit https://github.com/debrief/limpet/commit/0f369620184783fb86aa5ec53b5c7fa8cc930f5b

I have created a new issue related to integration: https://github.com/debrief/limpet/issues/224
I will check if we can use/find maven jacoco reporting.

@IanMayo 
Could you please let me know what exactly you want?
We can add link to coverage report from static reporting, but not sure if we can create the same/similar styling (at least it isn't too easily).

**Comment by pecko** [comment]
Closing this issue. Remaining issues/features will be solved in #224.
