### ISSUE TITLE
More on Checkstyle

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#226]
@pecko - could I have some more support in CheckStyle?

I want to tune the configuration to suit our styles.

Could you do the following:
- amend the pom.xml so that we have a checkstyle_checks.xml file in the top level folder
- fix the build process so that we can run `mvn clean verify site -U -B -fae` from the top level.  It's currently failing (see attached log file).
  [output.txt](https://github.com/debrief/limpet/files/78524/output.txt)

**Comment by pecko** [comment]
I have created the issue226 branch (commit: https://github.com/pecko/limpet/commit/43491aee0b1c4b7b5a5167d2e801094c22f363ef). It configures separate sun_checks_test.xml (it is copy of sun_checks.xml). You can play with that.

RE your error it is the OutOfMemory error. You can solve it by adding:

```
export MAVEN_OPTS="-Xmx1024M -Xms256M -XX:PermSize=128M -XX:MaxPermSize=256M"
```

before calling maven or to ~/.bashrc (on Linux). You can define environment variable MAVEN_OPTS on Windows.

If you use Java 8, you can remove "-XX:PermSize=128M -XX:MaxPermSize=256M".

BTW I haven't create a PR because it is just for your testing.
