### ISSUE TITLE
Clarify minimum steps to perform static code analysis, code coverage & unit tests

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#227]
I've documented the Mvn build process here:
https://github.com/debrief/limpet/wiki/AutomatedBuild

Is there a simpler set of commands that can be run to just perform the static code analysis & code coverage reporting?

Would you mind correcting/extending the guidance?

Aah, could you also extend the guidance to include the mvn update POM versions commands that we use for Debrief?

**Comment by pecko** [comment]
The following command are only required when building Eclipse first time and when we update target platform (for 3.8 to 4.x, for instance)

```
cd info.limpet.targetplatforms
mvn clean install
```

> Is there a simpler set of commands that can be run to just perform the static code analysis & code coverage reporting?

Code coverage reports are created with "mvn clean verify", but we will probably change it within #224 so it will be created as static code analysis.

Static code analysis reports are created with "mvn site", but, since, they require compiling, it is possible that they will not work properly without "mvn clean verify site..."

> Aah, could you also extend the guidance to include the mvn update POM versions commands that we use for Debrief?

That is the same as Debrief. However we will use limpet update site as part of target platform of Debrief (or some other application), so I propose the following:

We could set the same versions with qualifiers (1.0.6,qualifier, for instance) for all Limpet plugin/feature. The main version part (1.0.6) should be updated only if there are significant changes to 1.0.7, 1.0.8 ...When we change API so that Limpet isn't binary compatible with previous versions we would update to 1.1.x, 1.2.x ...
There is tycho plugin that update all version entries (pom.xml and MANIFEST.MF) with one command.

On the other hand, we will have a new (correct) update site whenever we push some commit to master (something like tern.core_1.0.6.201601061234 - 1234 is build number).

Eclipse and a lot other Eclipse project/plugin work in similar way.

**Comment by pecko** [comment]
Related to Mavn JVM option:

```
export MAVEN_OPTS="-Xmx1024M -Xms256M -XX:PermSize=128M -XX:MaxPermSize=256M"
```

is on Linux. For Java 8, we would use:

```
export MAVEN_OPTS="-Xmx1024M -Xms256M"
```

other options are deprecated in Java 8.

On Windows, it is

```
set MAVEN_OPTS=-Xmx1024M -Xms256M -XX:PermSize=128M -XX:MaxPermSize=256M
```

(set instead of and without ").
or define MAVEN_OPTS in Windows Environment.

**Comment by pecko** [comment]
@IanMayo 
I think that this issue can be closed.
