### ISSUE TITLE
Introduce concept of continuous dimension

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#251]
We have temporal quantity and object collections, where the measurements have a time aspect.

There are other datasets that have a relationship with another continuous dimension.  For an electric vehicle we may have a dataset containing mean power usage against speed.  If speed is treated as a continuous dimension, then we can interpolate the power usage for any particular speed.

So, if we have a dataset of time vs speed, we can select that plus the power usage-vs speed dataset and produce a dataset of time vs power usage.

Next, we can elect to color/shade the XY location plot with power usage (indexed by time).  This will effectively give us heatmap shading of power usage along the vehicles track.

**Update** Another example of this is a weather balloon ascent. The balloon readings are a function of altitude, not time.  So altitude (length) is the independent axis.

We should also consider if/how our treatment of time is a "special case".   The usage of time seems very clear so far.  But, is it that special?

We should also consider how this relates to other graphical plotting.  I guess that in our stacked plots we could elect to have any dimension on the X axis, and add any dataset that has that dimension.

So, I now believe TemporalXXX dataset is actually an extension of 2Dxxx dataset.

**Comment by dinkoivanov** [comment]
Completely agree that temporal collection can be generalized (perhaps simple rename-refactor) so that it does not assume timestamp as independent value.
The only thing that is specific to temporal collections is that timestamps are increasing, which might not be the case for other dimensions.
Right now the temporal collection inherits from the 1D collection. I think it would be a good idea to represent the 2Dxxx dataset as a composition of two 1D collections.

Side note: Another good example for 2D datasets are Well charts in the Oil&Gas domain. They always show the Measured depth as independent and various properties as a dependent value (such as pressure VS depth in the wellbore).

**Comment by IanMayo** [comment]
Resolved, following January integration.
