### ISSUE TITLE
Zoom to fit for GEF editor view

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#339]
The GEF edit view introduces scroll bars when it gets too tall.

Could you experiment with adding zoom to fit behaviour?

It will have to respond to a range of types of model change.  If this requires a lot of work, then it is satisfactory to just perform a zoom to fit when a new chart is added or removed.

**Comment by dinkoivanov** [comment]
Certain figures have hardcoded height (preferred size). The ChartFigure is 200 pixels high and the AxisLandingPadEditPart figure is 80 pixels high. This means they cannot be squeezed below those limits. If we remove those hardcoded heights, then we can add some more charts before we start seeing the vertical scrollbar. Check here:
![capture](https://cloud.githubusercontent.com/assets/4459598/15780074/99eaebe4-29a8-11e6-8e61-403259ae9106.PNG)
Note that now the 'minimum' height is defined by the length of the dataset and axis name labels in such a way that the text is not truncated. If we want the charts to become even smaller (in height), then we'll need to truncate the label or make font smaller. Another (very easy) option is to drop the "Dataset: " and "Axis: " prefixes in order to save space.
What do you think?

**Comment by IanMayo** [comment]
I have ordered some 16px icons, to use instead of that text.  I'll have a play next week, to consider your other suggestions.

## Update:

First version of icons received - though they may need some reworking to fit in 16px.
<img width="186" alt="screen shot 2016-06-06 at 10 15 03 am" src="https://cloud.githubusercontent.com/assets/1108513/15816266/e80e17ba-2bc9-11e6-88d7-eac5578df0a7.png">

**Comment by IanMayo** [comment]
Current implementation satisfactory
